
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author teddycormier
 */
public class RulesScreenWin extends javax.swing.JFrame {
    public GameScreenWin gameScreen;
    /**
     * Creates new form RulesScreen
     */
    public RulesScreenWin() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        back_button = new javax.swing.JButton();
        text_pane = new javax.swing.JScrollPane();
        text_in_pane = new javax.swing.JTextArea();
        bgr_rules = new javax.swing.JLabel();

        setTitle("RULES");
        setBounds(new java.awt.Rectangle(0, 25, 509, 340));
        setMinimumSize(new java.awt.Dimension(1000, 500));
        getContentPane().setLayout(null);

        back_button.setBackground(new java.awt.Color(204, 204, 204));
        back_button.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        back_button.setText("Back");
        back_button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        back_button.setBounds(new java.awt.Rectangle(900, 10, 60, 20));
        back_button.setMaximumSize(new java.awt.Dimension(60, 20));
        back_button.setMinimumSize(new java.awt.Dimension(60, 20));
        back_button.setPreferredSize(new java.awt.Dimension(60, 20));
        back_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(back_button);
        back_button.setBounds(900, 10, 60, 20);

        text_in_pane.setBackground(new java.awt.Color(0, 0, 0));
        text_in_pane.setColumns(20);
        text_in_pane.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        text_in_pane.setForeground(new java.awt.Color(204, 204, 0));
        text_in_pane.setRows(5);
        text_in_pane.setText("  \n  BEAT THE DEALER BY:\n\n   - Drawing a hand value that is higher than the dealer’s hand value\n   - The dealer drawing a hand value that goes over 21.\n   - Drawing a hand value of 21 on your first two cards, when the \n     dealer does not.\n\n\n  LOSE TO THE DEALER BY:\n\n   - Your hand value exceeds 21.\n   - The dealers hand has a greater value than yours at the end of\n     the round");
        text_pane.setViewportView(text_in_pane);

        getContentPane().add(text_pane);
        text_pane.setBounds(40, 100, 910, 290);

        bgr_rules.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sunset.png"))); // NOI18N
        getContentPane().add(bgr_rules);
        bgr_rules.setBounds(0, 0, 1000, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void back_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_buttonActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_back_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RulesScreenWin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RulesScreenWin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RulesScreenWin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RulesScreenWin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_button;
    private javax.swing.JLabel bgr_rules;
    private javax.swing.JTextArea text_in_pane;
    private javax.swing.JScrollPane text_pane;
    // End of variables declaration//GEN-END:variables
}
