
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author teddycormier
 */
public class StartScreenWin extends javax.swing.JFrame {
    GameScreenWin gameScreen;
    public static boolean closedHanded = false;
    /**
     * Creates new form Start
     */
    public StartScreenWin() throws IOException{
        initComponents();
        
        try {
            gameScreen = new GameScreenWin();
        } catch (InterruptedException ex) {
            Logger.getLogger(StartScreenWin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
     
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jColorChooser1 = new javax.swing.JColorChooser();
        header_label = new javax.swing.JLabel();
        open_handed_button = new javax.swing.JButton();
        closed_handed_button = new javax.swing.JButton();
        header_background = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("START");
        setBackground(new java.awt.Color(0, 0, 0));
        setBounds(new java.awt.Rectangle(0, 25, 505, 340));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(1000, 500));
        setSize(new java.awt.Dimension(1000, 500));
        getContentPane().setLayout(null);

        header_label.setFont(new java.awt.Font("Phosphate", 1, 14)); // NOI18N
        header_label.setForeground(new java.awt.Color(204, 204, 204));
        header_label.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        header_label.setText("BLACKJACK - BLACKJACK - BLACKJACK - BLACKJACK - BLACKJACK - BLACKJACK - BLACKJACK - BLACKJACK - BLACKJACK - BLACKJACK - BLACKJACK - BLACKJACK - BLACKJACK - BLACKJACK - ");
        getContentPane().add(header_label);
        header_label.setBounds(-24, 2, 1070, 10);

        open_handed_button.setBackground(new java.awt.Color(204, 204, 204));
        open_handed_button.setFont(new java.awt.Font("Times New Roman", 0, 8)); // NOI18N
        open_handed_button.setText("PLAY OPEN HANDED");
        open_handed_button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        open_handed_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                open_handed_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(open_handed_button);
        open_handed_button.setBounds(450, 230, 100, 30);

        closed_handed_button.setBackground(new java.awt.Color(204, 204, 204));
        closed_handed_button.setFont(new java.awt.Font("Times New Roman", 0, 8)); // NOI18N
        closed_handed_button.setText("PLAY CLOSED HANDED");
        closed_handed_button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        closed_handed_button.setMaximumSize(new java.awt.Dimension(30, 30));
        closed_handed_button.setMinimumSize(new java.awt.Dimension(30, 30));
        closed_handed_button.setPreferredSize(new java.awt.Dimension(30, 30));
        closed_handed_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closed_handed_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(closed_handed_button);
        closed_handed_button.setBounds(450, 270, 100, 30);

        header_background.setBackground(new java.awt.Color(0, 0, 0));
        header_background.setBorder(null);
        header_background.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                header_backgroundActionPerformed(evt);
            }
        });
        getContentPane().add(header_background);
        header_background.setBounds(-10, -4, 1040, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sunset.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1000, 500);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void open_handed_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_open_handed_buttonActionPerformed

        gameScreen.setLocationRelativeTo(null);
        gameScreen.setVisible(true);

        this.setVisible(false);
    }//GEN-LAST:event_open_handed_buttonActionPerformed

    private void header_backgroundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_header_backgroundActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_header_backgroundActionPerformed

    private void closed_handed_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closed_handed_buttonActionPerformed
        StartScreenWin.closedHanded = true;
        
        gameScreen.dealer_sum_label.setVisible(false);
        gameScreen.dealer_sum_total.setVisible(false);
        gameScreen.player_sum_label.setVisible(false);
        gameScreen.player_sum_total.setVisible(false);
        
        try {
            BufferedImage img = ImageIO.read(new File("/Users/teddycormier/NetBeansProjects/Blackjack/src/main/resources/backcard.png"));
            Image image = img.getScaledInstance(110, 160, Image.SCALE_DEFAULT);
            ImageIcon icon = new ImageIcon(img);
            gameScreen.closed_handed_card.setVisible(true);
            gameScreen.closed_handed_card.setIcon(icon);
        } catch (IOException ex) {
            Logger.getLogger(GameScreenWin.class.getName()).log(Level.SEVERE, null, ex);
        }
        gameScreen.setLocationRelativeTo(null);
        gameScreen.setVisible(true);

        this.setVisible(false);
    }//GEN-LAST:event_closed_handed_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws IOException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartScreenWin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartScreenWin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartScreenWin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartScreenWin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        StartScreenWin window = new StartScreenWin();
        window.setLocationRelativeTo(null);
        window.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closed_handed_button;
    private javax.swing.JButton header_background;
    private javax.swing.JLabel header_label;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton open_handed_button;
    // End of variables declaration//GEN-END:variables
}
